//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crmEntities : DbContext
    {
        public crmEntities()
            : base("name=crmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<company> companies { get; set; }
        public DbSet<in_order> in_order { get; set; }
        public DbSet<in_orderreceivelog> in_orderreceivelog { get; set; }
        public DbSet<in_orderreceivewarelog> in_orderreceivewarelog { get; set; }
        public DbSet<in_orderstatus> in_orderstatus { get; set; }
        public DbSet<in_orderware> in_orderware { get; set; }
        public DbSet<ware> wares { get; set; }
        public DbSet<ware_photo> ware_photo { get; set; }
        public DbSet<v_in_order> v_in_order { get; set; }
    }
}
