//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_orderware
    {
        public int ware_id { get; set; }
        public int order_id { get; set; }
        public int orderware_id { get; set; }
    }
}
