//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_orderreceivelog
    {
        public int order_id { get; set; }
        public Nullable<System.DateTime> startdatetime { get; set; }
        public Nullable<System.DateTime> finishdatetime { get; set; }
        public string videopath { get; set; }
        public string userbarcode { get; set; }
        public string messages { get; set; }
        public int orderreceivelog_id { get; set; }
    }
}
