//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_orderstatus
    {
        public int order_id { get; set; }
        public string status { get; set; }
        public System.DateTime setdate { get; set; }
        public string setuser { get; set; }
        public string comment { get; set; }
        public int orderstatus_id { get; set; }
    }
}
