//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_orderreceivewarelog
    {
        public int order_id { get; set; }
        public string barcode { get; set; }
        public byte[] photo { get; set; }
        public Nullable<System.DateTime> setdatetime { get; set; }
        public string messages { get; set; }
        public int orderreceivewarelog_id { get; set; }
    }
}
