//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_in_order
    {
        public int order_id { get; set; }
        public Nullable<System.DateTime> senddata { get; set; }
        public Nullable<System.DateTime> receivedata { get; set; }
        public string receiveuser { get; set; }
        public string number { get; set; }
        public string description { get; set; }
        public Nullable<int> company_id { get; set; }
        public string company_name { get; set; }
    }
}
