//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ware_photo
    {
        public int ware_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string filepath { get; set; }
        public int warephoto_id { get; set; }
        public Nullable<long> rank { get; set; }
    }
}
